name: xml_object_mapping_workspacae
description: A Dart library for mapping XML data to Dart objects using annotations.
version: 1.0.0
repository: https://github.com/infumia/xml_object_mapping
publish_to: none

workspace:
  - packages/xml_object_mapping
  - packages/xml_object_mapping_generator

environment:
  sdk: ^3.11.1

dev_dependencies:
  flint: ^2.14.0
  melos: ^7.4.0

melos:
  scripts:
    fix:
      run: dart fix --apply && dart format .
      exec:
        concurrency: 2
    get:
      run: flutter pub get
      exec:
        concurrency: 2
