name: xml_object_mapping_generator
description: A Dart library for mapping XML data to Dart objects using annotations.
version: 1.0.0
repository: https://github.com/infumia/xml_object_mapping
resolution: workspace

environment:
  sdk: ^3.11.1

dependencies:
  xml_object_mapping: ^1.0.0
  xml: ^6.6.1
  build: ^4.0.4
  source_gen: ^4.2.1
  analyzer: ">=9.0.0 <11.0.0"
  source_helper: ^1.3.10
  code_builder: ^4.11.1
