import "package:xml_object_mapping_example/models.dart";

void main() {
  const xmlText = '''
<user id="123">
  <name>John Doe</name>
  <email>john.doe@example.com</email>
  <roles>
    <role>Admin</role>
    <role>User</role>
  </roles>
  <profile>
    <bio>Software Engineer</bio>
    <website>https://example.com</website>
  </profile>
</user>
''';

  print("Parsing XML...");
  
  // The XmlUserMapper will be generated by build_runner
  final user = XmlUserMapper.parse(xmlText);

  print("Parsed User:");
  print("ID: ${user.id}");
  print("Name: ${user.name}");
  print("Email: ${user.email}");
  print("Roles: ${user.roles}");
  print("Profile Bio: ${user.profile?.bio}");
  print("Profile Website: ${user.profile?.website}");

  print("\nFull User Object:");
  print(user);
}
