// ignore_for_file: avoid_print

import "package:xml_object_mapping_example/advanced.dart";
import "package:xml_object_mapping_example/models.dart";

void main() {
  // Existing example
  runBasicExample();

  print("\n${"=" * 50}\n");

  // Advanced example
  runAdvancedExample();
}

void runBasicExample() {
  const xmlText = '''
<user id="123">
  <name>John Doe</name>
  <email>john.doe@example.com</email>
  <roles>
    <role>Admin</role>
    <role>User</role>
  </roles>
  <profile>
    <bio>Software Engineer</bio>
    <website>https://example.com</website>
  </profile>
</user>
''';

  print("--- Basic Example ---");
  print("Parsing XML...");

  // The UserXmlMapper will be generated by build_runner
  final user = UserXmlMapper.parse(xmlText);

  print("Parsed User:");
  print("ID: ${user.id}");
  print("Name: ${user.name}");
  print("Email: ${user.email}");
  print("Roles: ${user.roles}");
  print("Profile Bio: ${user.profile?.bio}");
  print("Profile Website: ${user.profile?.website}");

  print("\nFull User Object:");
  print(user);
}
