name: xml_object_mapping
description: A Dart library for mapping XML data to Dart objects using annotations.
version: 1.0.0
repository: https://github.com/infumia/xml_object_mapping
resolution: workspace

environment:
  sdk: ^3.11.1
